# Generated by Django 2.2.7 on 2019-12-22 12:22

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('bestnotes', '0003_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='content',
            field=tinymce.models.HTMLField(default='test', verbose_name='Content'),
            preserve_default=False,
        ),
    ]
